spring.config.import=optional:file:.env[.properties]
spring.application.name=leave-management-system

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
frontend.url=${FRONTEND_URL}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET_KEY}
spring.security.oauth2.client.registration.google.scope=${SCOPE}
spring.security.oauth2.client.registration.google.redirect-uri=${REDIRECT_URI}
spring.security.oauth2.client.provider.google.authorization-uri=${AUTHORIZATION_URI}

app.allowed-email-domain=${ALLOWED_EMAIL_DOMAIN}
google.calendar.id=${GOOGLE_CALENDAR_ID}
integration.google-calendar.enabled=${GOOGLE_CALENDAR_ENABLED:false}

google.calendar.api-base=${CALENDAR_BASE_API}
google.calendar.timezone=Asia/Kolkata

application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION}

app.cookie.expiration=${COOKIE_EXPIRATION}
app.cookie.secure=${COOKIE_SECURE}
app.cookie.same.site=${COOKIE_SAME_SITE}
app.frontend.url=${FRONTEND_URL}
app.redirect.frontend.url=${REDIRECT_FRONTEND_URL}

kimai.base-url=${KIMAI_BASE_URL}
kimai.api-token=${KIMAI_API_TOKEN}