spring.config.import=optional:file:.env[.properties]
spring.application.name=leave-management-system

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET_KEY}
spring.security.oauth2.client.registration.google.scope=${SCOPE}
spring.security.oauth2.client.registration.google.redirect-uri=${REDIRECT_URI}
app.allowed-email-domain=${ALLOWED_EMAIL_DOMAIN}

application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION}

app.cookie.expiration=${COOKIE_EXPIRATION}